---
- name: COPY 7repo to Server
  template: src=Centos-7.repo.j2 dest=/etc/yum.repos.d/CentOS7-Aliyun.repo backup=yes
  tags: yum
  when: install_7repo

- name: install gcc base init
  yum: name={{ item }} state=present
  with_items:
    - gcc
    - tree
    - dos2unix
    - net-tools
  when: install_gcc

