---
- name: COPY 7repo to Server
  template: src=Centos-7.repo.j2 dest=/etc/yum.repos.d/CentOS7-Aliyun.repo backup=yes
  tags: yum
  when: install_7repo

- name: COPY 7epel to Server
  template: src=epel-7.repo.j2 dest=/etc/yum.repos.d/epel-7-Aliyun.repo backup=yes
  tags: yum
  when: install_7repo

- name: install gcc base init
  yum:
    name:
      - gcc
      - tree
      - dos2unix
      - net-tools
    state: present
  when: install_gcc

