---
- name: Update Centos 6 yum source address
  include: centos6_repo.yml
  when: ansible_distribution == 'CentOS' and ansible_distribution_major_version == "6"

- name: Update Centos 7 yum source address
  include: centos7_repo.yml
  when: ansible_distribution == 'CentOS' and ansible_distribution_major_version == "7"

- include: Create_file.yml
  tags: create_dir

- name: Install redis2.8.0
  include: install_redis_2to5.yml
  when: ansible_distribution == 'CentOS' and redis_version == "2.8.0"


- name: Install redis3.2.0
  include: install_redis_2to5.yml
  when: ansible_distribution == 'CentOS' and redis_version == "3.2.0"

- name: Install redis4.0.0
  include: install_redis_2to5.yml
  when: ansible_distribution == 'CentOS' and redis_version == "4.0.0"


- name: Install redis5.0.0
  include: install_redis_2to5.yml
  when: ansible_distribution == 'CentOS' and redis_version == "5.0.0"